version: '2'
services:
  teamcity-server-instance:
    image: jetbrains/teamcity-server
    ports:
     - "8111:8111"
    restart: always
    volumes:
      - ~/test/teamcity/data:/data/teamcity_server/datadir
      - ~/test/teamcity/logs:/opt/teamcity/logs
    networks:
      - teamcity-network
 
  teamcity-agent-instance:
    image: jetbrains/teamcity-agent
    restart: always
    volumes:
      - ~/test/teamcity/agent-conf:/data/teamcity_agent/conf
      - ~/var/run/docker.sock:/var/run/docker.sock
    environment:
      - SERVER_URL=teamcity-server-instance:8111
      - DOCKER_IN_DOCKER=start
    networks:
      - teamcity-network
 
networks:
  teamcity-network: